title: Page

fields:
  title:
    label: Title
    type: title
    
  intro:
    label: Intro
    type: textarea
    
  text:
    label: Text
    type: textarea

  externalurl:
    label: Url
    type: URL